### ISSUE TITLE
ipv6支持

### ISSUE THREAD

**Issue by Droid-MAX** [honwen/aliyun-ddns-cli#16]
现在手机上已逐步普及ipv6，这使得在手机上建站成为了可能，虽然阿里云官方提供了相关api，但第三方的各种ddns工具对ipv6的支持都不大友好，所以在此还望大佬们可以为这个软件项目添加ipv6地址动态解析的功能，谢谢！

**Comment by chenhw2** [comment]
Pull requests are always welcome.

**Comment by Droid-MAX** [comment]
这个工具不能正常解析ipv6的原因貌似跟这个issue很像[Aliyun_DDNS](https://github.com/XAS-712/Aliyun_DDNS/issues/8)

**Comment by AndroidOL** [comment]
已记录，没有预计时间，会尽快解决。

**Comment by 873314461** [comment]
我刚刚提交了一个PR，目前可以正常更新IPv6地址，但是是否存在其他问题，还需要看情况

**Comment by honwen** [comment]
please help test
 - https://github.com/honwen/aliyun-ddns-cli/releases/tag/v2019-06-13
 - https://cloud.docker.com/repository/docker/chenhw2/aliyun-ddns-cli

**Comment by Droid-MAX** [comment]
可以手动指定ipv6，不过会报ipv4 format error错误，但可以成功修改

**Comment by 873314461** [comment]
> 可以手动指定ipv6，不过会报ipv4 format error错误，但可以成功修改

目前没有添加对IPv6格式的校验，添加校验之后应该可以自动识别地址的类型了

**Comment by Droid-MAX** [comment]
还有一个问题就是，如果默认不指定ipv6地址而通过web-api来获取的话，是无法正常更新记录的，只有使用-i参数手动指定一个ipv6地址才行

**Comment by honwen** [comment]
@Droid-MAX use `auto-update` with `-6`

```
NAME:
   aliyun-ddns-cli auto-update - Auto-Update AliYun's DNS DomainRecords Record, Get IP using its getip

USAGE:
   aliyun-ddns-cli auto-update [command options] [arguments...]

CATEGORY:
   DDNS

OPTIONS:
   --domain DomainName, -d DomainName  Specific DomainName. like ddns.aliyun.com
   --redo Seconds, -r Seconds          redo Auto-Update, every N Seconds; Disable if N less than 10; End with [Rr] enable random delay: [N, 2N]
   --ipv6, -6                          update IPv6 address
```

**Comment by Droid-MAX** [comment]
It works!

**Comment by ChnCdd** [comment]
使用--ipv6可以正常更新IPV6。但是会报“ipv4 format error”，同时IPV4也不能正常更新。
还有个问题就是三级域名b.a.domain.com不能正常更新，报“Status Code: 400 Code: InvalidDomainName.NoExist Message: The specified domain name does not exist. Refresh the page and try again.”。

**Comment by Droid-MAX** [comment]
update参数是用于手动指定ip来进行更新的，不过在更新ipv6地址时确实会报ipv4 format error，但不影响正常使用；而auto-update参数是自动通过getip来获取ip再进行更新的，这个是没问题的！

**Comment by 873314461** [comment]
>可以手动指定ipv6，不过会报ipv4 format error错误，但可以成功修改

@Droid-MAX 这个错误是因为找不到v6地址的位置信息导致的，新的PR已经修复了

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Droid-MAX** [comment]
目前来看，应该没有什么其他问题了

**Comment by Droid-MAX** [comment]
这次aliyun-ddns-cli的更新，会不会影响下游的luci-app-aliddns的正常使用呢？

**Comment by ChnCdd** [comment]
> 这次aliyun-ddns-cli的更新，会不会影响下游的luci-app-aliddns的正常使用呢？要不要再搞个repo名为openwrt-aliddns用于编译ipk配合luci-app-aliddns在openwrt上安装使用？

LEDE里有完美的插件，支持DNSPOD和ALI，可选IPV4和IPV6。

**Comment by honwen** [comment]
@Droid-MAX 两个都是独立的

**Comment by honwen** [comment]
please help test
 - https://github.com/honwen/aliyun-ddns-cli/releases/tag/v2019-06-19
 - https://cloud.docker.com/repository/docker/chenhw2/aliyun-ddns-cli
