### ISSUE TITLE
三级域名支持（b.a.domain.com）

### ISSUE THREAD

**Issue by ChnCdd** [honwen/aliyun-ddns-cli#20]
试了一下现在不能更新三级域名，会报错误
“Status Code: 400 Code: InvalidDomainName.NoExist Message: The specified domain name does not exist. Refresh the page and try again.”。

**Comment by ChnCdd** [comment]
看了一下可能和“main.go”中函数“CheckAndUpdateRecord”里的变量rr和domain有关？
是否修正一下正则匹配就行？
我不懂go语言，猜的。

**Comment by 873314461** [comment]
目前使用fulldomain的方式很难适应多级域名，因为没法确定你的记录值是什么，所以暂时不好修改

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by honwen** [comment]
三级域名建议采用CNAME的方式

**Comment by Droid-MAX** [comment]
@honwen 赞同
