### ISSUE TITLE
InvalidDomainName.NoExist

### ISSUE THREAD

**Issue by czeludzki** [honwen/aliyun-ddns-cli#22]
Thanks for the great code.
It worked fine a few days ago, but has been prompting this error since recently, which I caught from the docker log:

> `"Aliyun API Error: RequestId: XXXXXXXX - XXXX - XXXX - XXXX - XXXXXXX Status Code: 400 Code: InvalidDomainName. NoExist Message: The specified domain name does not exist. Refresh The page and try again."

**Comment by honwen** [comment]
After this log, does DDNS still work?
if so, this error log can be ignore

**Comment by czeludzki** [comment]
> After this log, does DDNS still work?
> if so, this error log can be ignore

Uh..NO, I have checked the domain name resolution and it does not point to the correct IP address , that's why I issuesed.
In my opinion, the error was caused by something has changed of aliyun's API..

**Comment by honwen** [comment]
delete domain in aliyun and try again

**Comment by czeludzki** [comment]
> delete domain in aliyun and try again

ok, I'll try, thanks

**Comment by honwen** [comment]
I check upstream package [aliyungo](https://github.com/denverdino/aliyungo), module `dns` haven't change for a long time

**Comment by czeludzki** [comment]
I have tried, it still log the same error.
but I have found clues...
I created a new docker container: `DOMAIN=abc.domain.com`, it work fine...
then I created another docker container: `DOMAIN=abc.cba.domain.com`, same error again...
It doesn't seem to support three-level domains

**Comment by honwen** [comment]
> It doesn't seem to support three-level domains

YES, it dont

https://github.com/honwen/aliyun-ddns-cli/issues/20

**Comment by czeludzki** [comment]
> > It doesn't seem to support three-level domains
> 
> YES, it dont
> 
> #20

好的, 感谢!

**Comment by LarryBrin** [comment]
想知道最终你的mac电池放气后, 换电池了吗?

**Comment by LarryBrin** [comment]
> > > It doesn't seem to support three-level domains
> > 
> > 
> > YES, it dont
> > #20
> 
> 好的, 感谢!

你的mac电池放气后, 换电池了吗?
正在纠结要不要换呢?
感觉网上面的电池都不靠谱~~~~~~~~

**Comment by honwen** [comment]
i dont know what U R saying

Hongyuan Shao <notifications@github.com>于2019年9月29日 周日23:13写道：
