### ISSUE TITLE
Status Code: 404 Code: InvalidAccessKeyId.NotFound Message: Specified access key is not found.

### ISSUE THREAD

**Issue by nishuo** [honwen/aliyun-ddns-cli#24]
2019/10/08 14:50:56 hk-10.crhnode.top 119.236.X.X [中国 香港 ]
2019/10/08 14:53:34 Aliyun API Error: RequestId: 61671224-9C93-440F-8962-FBBA450296E2 Status Code: 404 Code: InvalidAccessKeyId.NotFound Message: Specified access key is not found.
2019/10/08 14:56:06 Aliyun API Error: RequestId: 38951641-55C1-4C6E-86D6-091EBDED9C3E Status Code: 404 Code: InvalidAccessKeyId.NotFound Message: Specified access key is not found.
2019/10/08 14:58:37 Aliyun API Error: RequestId: E8FF43B1-55BC-4164-AF9C-F0E5AA1CE0F3 Status Code: 404 Code: InvalidAccessKeyId.NotFound Message: Specified access key is not found.

**Comment by nishuo** [comment]
确认AccessKey ID   Access Key Secret正确
尝试创建新的ID Key，重试一样404.. 
尝试创建子账号分配解析权限，使用子账号的ID key 404
作者有时间看看吗..远程复现一下 
阿里的说

>  售后工程师 :    2019/10/08 14:53:34 Aliyun API Error: RequestId: 61671224-9C93-440F-8962-FBBA450296E2 Status Code: 404 Code: InvalidAccessKeyId.NotFound Message: Specified access key is not found.
这个requestId 的报错原因是您请求时，使用的key不存在。在key中，前后多了一组中括号，可能是您的代码有问题，还请查看一下。

**Comment by honwen** [comment]
use AccessKey instead SubAccessKey

**Comment by honwen** [comment]
I check with my aliyun sub-account, it works.

![image](https://user-images.githubusercontent.com/12322033/66387916-9820ef80-e9f7-11e9-93fa-891268de3e33.png)

![image](https://user-images.githubusercontent.com/12322033/66387952-abcc5600-e9f7-11e9-8881-3b14cea0ddad.png)

**Comment by nishuo** [comment]
![Snipaste_2019-10-08_18-25-10.png](https://i.loli.net/2019/10/08/mdbwIHFX57xtYOQ.png)
![Snipaste_2019-10-08_18-24-44.png](https://i.loli.net/2019/10/08/3Bog19iKRYQTx6W.png)
![Snipaste_2019-10-08_18-26-10.png](https://i.loli.net/2019/10/08/UFbZPVCr3RjD5zo.png)

**Comment by nishuo** [comment]
.............没有删除中括号。我傻了
