### ISSUE TITLE
无法自动更新ipv6了

### ISSUE THREAD

**Issue by Droid-MAX** [honwen/aliyun-ddns-cli#29]
getip -6没有输出任何地址，auto-update -6提示错误码400，Status Code: 400 Code: MissingValue Message: Value is mandatory for this action.
但是手动调用api(只有两个ipv6的api可以正常返回ipv6地址)却可以正常查询返回ipv6地址，能直接访问ipv6站点，但访问ipv6-test网站时提示不支持ipv6，dns服务器支持ipv6，其实是可以正常访问ipv6的。不确定是dns的问题还是其他问题。。。头都大了

**Comment by Droid-MAX** [comment]
新增了一个ipv6地址查询接口[东北大学网络测速网站](https://github.com/honwen/aliyun-ddns-cli/pull/30)
还没编译测试，不过手动请求有正常返回，应该能解决这个问题。

**Comment by Droid-MAX** [comment]
问题已解决！

**Comment by Droid-MAX** [comment]
![image](https://user-images.githubusercontent.com/12762435/80777659-86bc5200-8b98-11ea-9224-a86a930e530a.png)
这个接口经常会请求超时。

**Comment by honwen** [comment]
Thanks a lot, I DONT have a regular IPv6-ENV to develop related feature.
