### ISSUE TITLE
怎么添加两个解析记录

### ISSUE THREAD

**Issue by Hu-Sea** [honwen/aliyun-ddns-cli#33]
-e "DOMAIN=ddns.aliyun.win" \

这里默认只有一个记录，一般为 www.aliyun.com
如果想加入另一个记录  @.aliyun.com
该如何操作？

**Comment by Hu-Sea** [comment]
There is only one record by default, generally   www.aliyun.com
If you want to add another record    @.aliyun.com
How to operate?

**Comment by honwen** [comment]
`CNAME`, refer #32
