### ISSUE TITLE
chenhw2/aliyun-ddns-cli Query IP Format error.

### ISSUE THREAD

**Issue by fjlaile** [honwen/aliyun-ddns-cli#41]
如题，不知道是什么原因，我使用的是unraid 6.8.2 的docker安装

**Comment by honwen** [comment]
more info/log?

**Comment by fjlaile** [comment]
@honwen the log just show:
2020/12/28 18:18:23 Query IP Format error.
www.XXXXXX
2020/12/28 18:08:10 Query IP Format error.
.........

**Comment by honwen** [comment]
exec in to container and `curl -Lv myip.ipip.net`

**Comment by fjlaile** [comment]
@honwen follow the setp,it show:
/ # curl -LV myip.ipip.net
curl 7.69.1 (x86_64-alpine-linux-musl) libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

**Comment by honwen** [comment]
`v` not `V`

**Comment by fjlaile** [comment]
@honwen sorry , it show:
/ # curl -Lv myip.ipip.net
* Could not resolve host: myip.ipip.net
* Closing connection 0
curl: (6) Could not resolve host: myip.ipip.net

**Comment by honwen** [comment]
Ur network probelm

**Comment by fjlaile** [comment]
@honwen ok....thank you always~
