### ISSUE TITLE
Query IP Format error

### ISSUE THREAD

**Issue by jqorz** [honwen/aliyun-ddns-cli#43]
I get this error in log. And I get the response when I execute 'curl'
`curl -Lv myip.ipip.net
> GET / HTTP/1.1
> Host: myip.ipip.net
> User-Agent: curl/7.54.0
> Accept: */*
当前 IP： xx 来自于：中国 安徽 合肥  电信

**Comment by honwen** [comment]
full log?

**Comment by jqorz** [comment]
Full log is here.

* Rebuilt URL to: myip.ipip.net/
*   Trying 117.23.61.188...
* TCP_NODELAY set
* Connected to myip.ipip.net (117.23.61.188) port 80 (#0)
> GET / HTTP/1.1
> Host: myip.ipip.net
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 04 Feb 2021 14:52:38 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 69
< Connection: keep-alive
< X-Via-JSL: 1d9bd9a,-
< Set-Cookie: __jsluid_h=ca044f40e1c04da6c0c5103fa37c6db3; max-age=31536000; path=/; HttpOnly
< X-Cache: bypass
<
当前 IP：xx  来自于：中国 安徽 合肥  电信

**Comment by honwen** [comment]
full log of `aliyun-ddns-cli`

**Comment by jqorz** [comment]
在容器里启动新的终端的时候，报错了
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused “exec: “/bin/bash”: stat /bin/bash: no such file or directory”: unknown

**Comment by honwen** [comment]
use `/bin/ash` instead

**Comment by jqorz** [comment]
I get the log here:  

> Could not resolve host 

And I get the reason, because I set the wrong firewall rule . 
Sorry about that.
