### ISSUE TITLE
调用阿里接口返回 MissingValue

### ISSUE THREAD

**Issue by WinteWu** [honwen/aliyun-ddns-cli#44]
日志如下

2021/02/20 13:54:27 Aliyun API Error: RequestId: C27674D1-73DD-440A-8281-1A6FC16C7C31 Status Code: 400 Code: MissingValue Message: Value is mandatory for this action. | stdout
-- | --

**Comment by WinteWu** [comment]
找到问题了，是因为我切换了网站https证书导致的，当前的网站证书不受curl、wget支持，导致没有获取到ip
自建的api： whatismyip.wintewu.com

**Comment by honwen** [comment]
> 找到问题了，是因为我切换了网站https证书导致的，当前的网站证书不受curl、wget支持，导致没有获取到ip
> 自建的api： whatismyip.wintewu.com

solved
