### ISSUE TITLE
多个主机名相同时设置解析

### ISSUE THREAD

**Issue by Dreamupers** [honwen/aliyun-ddns-cli#46]
在DNS服务器中为同一个主机记录配置多个IP地址，在应答DNS查询时，所有IP地址按照预先设置的权重进行返回不同的解析结果，将解析流量分配到不同的服务器上，从而达到负载均衡的目的。
![image](https://user-images.githubusercontent.com/49057488/110288680-5698d780-8023-11eb-9dce-f862d6c46807.png)
那么如何指定修改某个记录的IP呢

**Comment by honwen** [comment]
not a `DDNS` designed usage?
