### ISSUE TITLE
可否加入ttl设置？

### ISSUE THREAD

**Issue by LuffyesMa** [honwen/aliyun-ddns-cli#50]
可否加上阿里云ttl的设置。。默认是600秒。。

**Comment by honwen** [comment]
min=600, why not use min?

**Comment by LuffyesMa** [comment]
![image](https://user-images.githubusercontent.com/27800714/120881761-0fac8500-c606-11eb-818b-b8cc3b6c8f97.png)

**Comment by honwen** [comment]
![2021-06-05 14-01-39屏幕截图](https://user-images.githubusercontent.com/12322033/120881846-95303500-c606-11eb-9025-d4e901dc5d9a.png)

seems that my free service CAN NOT set <10m

---

btw, pr is always welcome

**Comment by runchunzhang** [comment]
Alibaba cloud can purchase services to reduce the TTL to 60s.
Could we add a new TTL parameter? The default is 600.
![image](https://user-images.githubusercontent.com/18542704/131451200-13baee4f-da10-42e8-a2a1-6620650ec552.png)

**Comment by xzxiaoshan** [comment]
> 可否加上阿里云ttl的设置。默认是600秒。。

已经提交了 PR，https://github.com/honwen/aliyun-ddns-cli/pull/55  
其他急用这个功能的小伙伴可以用镜像  xzxiaoshan/aliyun-ddns-cli:ttl ，截止作者合并PR之前，增加了TTL参数（我已经在用了，运行正常，仅仅是多了一个TTL参数）

**Comment by honwen** [comment]
Please Help Test `Pre-Release`: https://github.com/honwen/aliyun-ddns-cli/releases/tag/v2021-10-31

**Comment by runchunzhang** [comment]
![image](https://user-images.githubusercontent.com/18542704/140595749-c26d8390-76ab-4cd1-af63-3455b5b7dd4a.png)

ttl works
