### ISSUE TITLE
NAS docker 打开 ipv6 提示命令行格式错误

### ISSUE THREAD

**Issue by caelanyang** [honwen/aliyun-ddns-cli#52]
问题如上
命令行格式如下：
/bin/sh -c aliyun-ddns-cli   --ipapi ${IPAPI}  auto-update   --ipv6    --domain ${DOMAIN}    --redo ${REDO}  
/bin/sh -c aliyun-ddns-cli   --ipapi ${IPAPI}  --ipv6 auto-update      --domain ${DOMAIN}    --redo ${REDO}  
试了很多种格式包括如上两种，但是一直是格式错误，想问一下正确的格式怎样的。。

**Comment by honwen** [comment]
set env `IPV6`=`1`

refer: https://github.com/honwen/aliyun-ddns-cli/blob/master/Dockerfile#L27

**Comment by caelanyang** [comment]
> set env `IPV6`=`1`
> 
> refer: https://github.com/honwen/aliyun-ddns-cli/blob/master/Dockerfile#L27

谢谢，这样设置是可以运行了。不过日志里面一直报错，  Err-CheckAndUpdateRecord: [IP is empty, PLZ check network]。
我使用 ssh ifconfig 能够获取到 ipv6 地址，手动 copy 到阿里云解析哪里也是能够外网访问的。能帮助看下什么原因吗，多谢

**Comment by caelanyang** [comment]
> > set env `IPV6`=`1`
> > refer: https://github.com/honwen/aliyun-ddns-cli/blob/master/Dockerfile#L27
> 
> 谢谢，这样设置是可以运行了。不过日志里面一直报错， Err-CheckAndUpdateRecord: [IP is empty, PLZ check network]。
> 我使用 ssh ifconfig 能够获取到 ipv6 地址，手动 copy 到阿里云解析那里也是能够外网访问的。能帮助看下什么原因吗，多谢

另外，我的网络环境以及NAS ssh 都能够代码里这几个网址 http://speed.neu6.edu.cn/getIP.php  http://v6.myip.la 获得 ipv6 地址

**Comment by honwen** [comment]
docker ipv6 network is NOT enabled by default, try use network=host

**Comment by caelanyang** [comment]
> docker ipv6 network is NOT enabled by default, try use network=host

thx, it works
