### ISSUE TITLE
Got temp IPV6 on Windows 10

### ISSUE THREAD

**Issue by rickywu** [honwen/aliyun-ddns-cli#56]
As described, not use correct one and can it support run in backgroud on Windows?

I use
aliddns.exe -6 --id xx --secret xx auto-update --domain xx.abc.cf --redo 60

**Comment by honwen** [comment]
try use with https://github.com/pandolia/easy-service

refer doc https://cloud.tencent.com/developer/article/1617131

**Comment by honwen** [comment]
for ipv6, i dont have ipv6 env to debug this

**Comment by rickywu** [comment]
@honwen I think the problem is here https://github.com/honwen/golibs/blob/dfcecd902aa2ec2e89dcacc09d4ecbe7df2efc05/cip/api.go#L66

This line got the last one ipv6 addr, but in windows should get the first one

**Comment by honwen** [comment]
> @honwen I think the problem is here https://github.com/honwen/golibs/blob/dfcecd902aa2ec2e89dcacc09d4ecbe7df2efc05/cip/api.go#L66
> 
> This line got the last one ipv6 addr, but in windows should get the first one

this func return the most common one ip addr, not the last-one.

----
if there is any ip-api return wrong ip?
try modfiy https://github.com/honwen/golibs/blob/dfcecd902aa2ec2e89dcacc09d4ecbe7df2efc05/cip/api.go#L19

**Comment by rickywu** [comment]
all apis return temprarily ipv6 address, so let it go
