### ISSUE TITLE
有考虑加入支持arm的docker镜像吗？

### ISSUE THREAD

**Issue by JacianLiu** [honwen/aliyun-ddns-cli#59]
arm下容器启动报错

![image](https://user-images.githubusercontent.com/45160423/149565079-44ecbefc-c1c0-4861-a227-a767cc57bce1.png)

**Comment by honwen** [comment]
DONT have ARM env, PR is always welcome.

**Comment by antnesswcm** [comment]
我直接用[releases](https://github.com/honwen/aliyun-ddns-cli/releases)里的arm版本配合shell脚本实现了ddns

**Comment by michaelauto** [comment]
> arm下容器启动报错
> 
> ![image](https://user-images.githubusercontent.com/45160423/149565079-44ecbefc-c1c0-4861-a227-a767cc57bce1.png)

你这arm架构当然运行不了
