### ISSUE TITLE
获取IP的网址是哪个？

### ISSUE THREAD

**Issue by haoping1** [honwen/aliyun-ddns-cli#62]
用了科学上网需要把获取IP的网址加入到白名单

**Comment by honwen** [comment]
read the readme

**Comment by ufoozhenghao** [comment]
> read the readme

大佬 readme只是说了`getip          Get IP Combine 10+ different Web-API` 具体是那些网址啊？

**Comment by honwen** [comment]
> > read the readme
> 
> 大佬 readme只是说了`getip Get IP Combine 10+ different Web-API` 具体是那些网址啊？

https://github.com/honwen/golibs/blob/master/cip/api.go#L12

set Ur own api with args: `--ipapi` if needed
