### ISSUE TITLE
请问可以一次同步多个域名吗

### ISSUE THREAD

**Issue by antnesswcm** [honwen/aliyun-ddns-cli#65]
例如我需要将
1.1.1.1-->a.xxx.com   第一项
2.2.2.2-->b.xxx.com   第二项

对于第一项，我可以
./aliddns --id ${ID} --secret ${KEY} --ipv6 update --domain a.xxx.com--ipaddr 1.1.1.1

那么
我要在一次调用aliddns 时完成两项的同步应该怎么做呢
求教，感谢

**Comment by honwen** [comment]
if `1.1.1.1` == `2.2.2.2`: use `CNAME`
else: execute multiple times
