### ISSUE TITLE
新版解析出来的IP总变成国外ip，这种怎么处理？

### ISSUE THREAD

**Issue by wangzhili888** [honwen/aliyun-ddns-cli#66]
![2022-05-10_10-47-14](https://user-images.githubusercontent.com/37832667/167532963-c2200f72-b0ef-4bc6-8b7a-a35e5fd6bb89.png)

**Comment by honwen** [comment]
try ass args `--ipapi=`, value refer: https://github.com/honwen/golibs/blob/master/cip/api.go#L12

**Comment by honwen** [comment]
try https://github.com/honwen/aliyun-ddns-cli/releases/tag/v2022-05-13
