### ISSUE TITLE
多个域名的语法 multiple domain at the same time

### ISSUE THREAD

**Issue by ryangu18** [honwen/aliyun-ddns-cli#67]
在用chenhw2/aliyun-ddns-cli做域名解析时，如果是同时多个域名，如何设置DOMAIN= 这里的参数？
我尝试过，如果单独写，每个解析都正常，但不知道怎么实现同时解析不同的域名。
When I use chenhw2/aliyun-ddns-cli for ddns, if there are multiple domain names at the same time, how to set the DOMAIN= parameter here? I have tried it, and if I write it separately, each ddns was fine, but I don't know how to use different domain names at the same time.

![image](https://user-images.githubusercontent.com/99937589/168529336-3b1b798b-cb1d-40c5-a15b-c6232cadc5e6.png)
![image](https://user-images.githubusercontent.com/99937589/168529349-46d29440-c211-439d-b15c-fa8e695fe5e5.png)

希望能得到帮助，提前感谢
thanks in advance

**Comment by honwen** [comment]
https://github.com/honwen/aliyun-ddns-cli/issues/38
