### ISSUE TITLE
2022/07/05 08:45:21 # Err-CheckAndUpdateRecord: [domain[@.XXXX.XXX] reslove empty, PLZ check network]

### ISSUE THREAD

**Issue by ahunigel** [honwen/aliyun-ddns-cli#70]
在DSM 7.1上总是运行不起来，报下面的错
```
2022/07/05 08:45:21 # Err-CheckAndUpdateRecord: [domain[@.XXXX.XXX] reslove empty, PLZ check network]
```

**Comment by ShuBo6** [comment]
没有查到域名的解析记录，请检查网络。如果网络正常的话，有可能是域名解析控制台没有添加过A记录解析。

**Comment by ahunigel** [comment]
> 没有查到域名的解析记录，请检查网络。如果网络正常的话，有可能是域名解析控制台没有添加过A记录解析。

那不可能，换成 sanjusss/aliyun-ddns 是可以正常解析的

**Comment by WACrown** [comment]
确实有这个问题，解决了吗

**Comment by ahunigel** [comment]
我换成 sanjusss/aliyun-ddns了

**Comment by iandyilove** [comment]
我是群呼7.*，开始使用也是报这个错误，换成sanjusss/aliyun-ddns秒成功。感谢这个帖子。

**Comment by ahunigel** [comment]
> 我是群晖7.*，开始使用也是报这个错误，换成sanjusss/aliyun-ddns秒成功。感谢这个帖子。

希望作者能修复这个问题吧，毕竟占得内存小一些 ：）

**Comment by L1ttleBad** [comment]
遇到了同样的问题，仅对@主机域名出现，下面的子域名比如www.aliyun.mv就能够更新成功，aliyun.mv就报这个错误

**Comment by iancsy** [comment]
DSM 7.1 同样问题，reslove empty，求解决，和时间不一致有关吗？

**Comment by gdxieyue** [comment]
先在阿里云配置www.abc.mv的解析，然后配置docker环境变量 DOMAIN=www.abc.mv，启动即可。

“主机记录就是域名前缀，常见用法有：
www：解析后的域名为www.aliyun.com。”

**Comment by wuyi316904** [comment]
QNAP QTS5.0系统，试过www.abc.com是OK的，abc.com的话会报empty错误，希望有人能解决。
还有一个问题顺便问一下，docker创建以后，还能修改配置吗？每次配置错了都是删除重新安装，也挺麻烦

**Comment by aizhouyi** [comment]
我也是，找半天最后猜测可能镜像的问题，来找了，用回以前的容器是没问题的，一毛一样的症状

**Comment by ahunigel** [comment]
> 我也是，找半天最后猜测可能镜像的问题，来找了，用回以前的容器是没问题的，一毛一样的症状。 补充下可能需要的信息，原来的镜像用的是版本是ALIDDNS Git:[2EE6F5330D@2022-01-07] (go1.17.6)，这个没问题。 现在是ALIDDNS Git:[V2022-08-10@0616FB1DF7] (go1.18.5)

我的是ALIDDNS Git:[V2022-06-24@86431E4B29] (go1.18.3)，准备下个ALIDDNS Git:[2EE6F5330D@2022-01-07] (go1.17.6)试试

**Comment by ahunigel** [comment]
> > 我也是，找半天最后猜测可能镜像的问题，来找了，用回以前的容器是没问题的，一毛一样的症状。 补充下可能需要的信息，原来的镜像用的是版本是ALIDDNS Git:[2EE6F5330D@2022-01-07] (go1.17.6)，这个没问题。 现在是ALIDDNS Git:[V2022-08-10@0616FB1DF7] (go1.18.5)
> 
> 我的是ALIDDNS Git:[V2022-06-24@86431E4B29] (go1.18.3)，准备下个ALIDDNS Git:[2EE6F5330D@2022-01-07] (go1.17.6)试试

群晖自带docker没法选版本。。。

**Comment by aizhouyi** [comment]
> > > 我也是，找半天最后猜测可能镜像的问题，来找了，用回以前的容器是没问题的，一毛一样的症状。 补充下可能需要的信息，原来的镜像用的是版本是ALIDDNS Git:[2EE6F5330D@2022-01-07] (go1.17.6)，这个没问题。 现在是ALIDDNS Git:[V2022-08-10@0616FB1DF7] (go1.18.5)
> > 
> > 
> > 我的是ALIDDNS Git:[V2022-06-24@86431E4B29] (go1.18.3)，准备下个ALIDDNS Git:[2EE6F5330D@2022-01-07] (go1.17.6)试试
> 
> 群晖自带docker没法选版本。。。

不是没法选择版本，作者就只保留了两个，一个latset，一个ttl，ttl（2021年10月31日）的能用。
嗨，我以前的容器还没删，直接用回以前的容器了。

**Comment by ahunigel** [comment]
> > > > 我也是，找半天最后猜测可能镜像的问题，来找了，用回以前的容器是没问题的，一毛一样的症状。 补充下可能需要的信息，原来的镜像用的是版本是ALIDDNS Git:[2EE6F5330D@2022-01-07] (go1.17.6)，这个没问题。 现在是ALIDDNS Git:[V2022-08-10@0616FB1DF7] (go1.18.5)
> > > 
> > > 
> > > 我的是ALIDDNS Git:[V2022-06-24@86431E4B29] (go1.18.3)，准备下个ALIDDNS Git:[2EE6F5330D@2022-01-07] (go1.17.6)试试
> > 
> > 
> > 群晖自带docker没法选版本。。。
> 
> 不是没法选择版本，作者就只保留了两个，一个latset，一个ttl，ttl（2021年10月31日）的能用。 嗨，我以前的容器还没删，直接用回以前的容器了。

![image](https://user-images.githubusercontent.com/8499085/192743542-90da3dbe-c419-4e92-aa5d-81bb331d30f8.png)
TTL已经变城2022的了

**Comment by honwen** [comment]
fixed https://github.com/honwen/aliyun-ddns-cli/commit/643313a72a2f39c9dce9a243a63a0f2b7d5c0e13

**Comment by ahunigel** [comment]
ttl还是（2021年10月31日）呀

**Comment by honwen** [comment]
> ttl还是（2021年10月31日）呀

@ahunigel `TTL` feature was merged, plese use `:lastet`

**Comment by ahunigel** [comment]
Thanks for the update, I will try it later
