### ISSUE TITLE
不能对容器设置时区

### ISSUE THREAD

**Issue by lnc1995** [honwen/aliyun-ddns-cli#83]
TZ参数无法被识别，会导致有些Docker环境下时间不正确

**Comment by honwen** [comment]
Try lastet image

**Comment by lnc1995** [comment]
> Try lastet image

Seems not work.I have already add TZ=Asia/Shanghai parameter.
OS:RouterOS x86 7.12.1

**Comment by honwen** [comment]
try remove thw TZ env

**Comment by lnc1995** [comment]
![SmartSelect_20231218_103049_MikroTik](https://github.com/honwen/aliyun-ddns-cli/assets/27806498/c541814c-b843-4402-bba7-b2fcd41cad8c)
As you can see, there is a difference of 8 hours between my time and the time in the container

**Comment by lnc1995** [comment]
> try remove thw TZ env

Awesome！ It works！Thanks a lot！
